# Generated by Django 6.0.4 on 2026-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_solarrequest_appliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='request',
            new_name='solar_request',
        ),
        migrations.RemoveField(
            model_name='solarrequest',
            name='total',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
