# Generated by Django 6.0.4 on 2026-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_request_appliance_solar_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarOnlyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('battery_qty', models.IntegerField()),
                ('inverter_power', models.CharField(max_length=50)),
                ('voltage', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
