# Generated by Django 6.0.4 on 2026-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarrequest',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
